# Generated by Django 5.1.5 on 2025-02-04 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudyCourse',
            new_name='StudyProgram',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='studyCourse',
            new_name='studyProgram',
        ),
        migrations.RenameField(
            model_name='interviewmodel',
            old_name='studyCourse',
            new_name='studyProgram',
        ),
    ]
