# Generated by Django 5.1.5 on 2025-02-05 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_studycourse_studyprogram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewmodel',
            name='studyProgram',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.studyprogram'),
        ),
    ]
