# Generated by Django 5.1.5 on 2025-02-06 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_interviewmodel_studyprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewmodel',
            name='studyProgram',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviewModel', to='main.studyprogram'),
        ),
    ]
