# Generated by Django 5.1.5 on 2025-02-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_interviewmodel_studyprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewmodel',
            name='questionsList',
            field=models.ManyToManyField(null=True, related_name='interview_questions', to='main.question'),
        ),
    ]
