# Generated by Django 5.1.5 on 2025-02-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_interviewmodel_questionslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewmodel',
            name='questionsList',
            field=models.ManyToManyField(blank=True, null=True, related_name='interview_questions', to='main.question'),
        ),
    ]
