# Generated by Django 5.1.5 on 2025-02-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_interviewmodel_questionslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
