# Generated by Django 5.1.5 on 2025-02-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('general', 'General Question'), ('knowledge', 'With right answer')], max_length=12),
        ),
    ]
