# Generated by Django 5.1.5 on 2025-02-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_interviewmodel_questionslist_question_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('factual', 'General Question'), ('knowledge', 'With right answer')], max_length=12),
        ),
    ]
