# Generated by Django 5.1.5 on 2025-02-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='maxTime',
            field=models.IntegerField(default=60, null=True),
        ),
    ]
