# Generated by Django 5.1.5 on 2025-02-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_question_maxtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewmodel',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('uncomplete', 'Uncomplete')], default='uncomplete', max_length=11),
        ),
    ]
