# Generated by Django 5.1.5 on 2025-03-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_interviewmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
