# Generated by Django 5.1.5 on 2025-04-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_applicant_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogram',
            name='coursePicture',
            field=models.ImageField(blank=True, null=True, upload_to='course_pictures/'),
        ),
    ]
