# Generated by Django 5.1.5 on 2025-04-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_studyprogram_coursepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogram',
            name='courseDescription',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='courseLanguage',
            field=models.CharField(default='ENG', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='studyLevel',
            field=models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], default='Bachelor', max_length=10),
            preserve_default=False,
        ),
    ]
