# Generated by Django 5.1.5 on 2025-05-17 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_studyprogram_coursedescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductedinterview',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('in progress', 'In Progress')], default='in progress', max_length=12),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL),
        ),
    ]
