# Generated by Django 5.1.5 on 2025-05-17 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_conductedinterview_status_alter_applicant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductedinterview',
            name='score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
