# Generated by Django 5.1.5 on 2025-05-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_interviewanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='audio_response',
            field=models.FileField(blank=True, null=True, upload_to='audio_responses/'),
        ),
    ]
