# Generated by Django 5.1.5 on 2025-05-19 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_interviewanswer_audio_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='model_comment',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
